// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4O1RUpXPshz2cXIrInINKMh89bTYa89o',
    appId: '1:383298804056:web:1b53e4b1d642409acced2d',
    messagingSenderId: '383298804056',
    projectId: 'thesisproject-f33a2',
    authDomain: 'thesisproject-f33a2.firebaseapp.com',
    storageBucket: 'thesisproject-f33a2.firebasestorage.app',
    measurementId: 'G-S3QDZXQK8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjM2zeH4MrFqt9juJkRXM6wTTjfbN7eu4',
    appId: '1:383298804056:android:69cecdaa5d3cdeedcced2d',
    messagingSenderId: '383298804056',
    projectId: 'thesisproject-f33a2',
    storageBucket: 'thesisproject-f33a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARYoZEEirAqiUJy-bS3u4ByoeON392NUA',
    appId: '1:383298804056:ios:523d14cbeb70cf82cced2d',
    messagingSenderId: '383298804056',
    projectId: 'thesisproject-f33a2',
    storageBucket: 'thesisproject-f33a2.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARYoZEEirAqiUJy-bS3u4ByoeON392NUA',
    appId: '1:383298804056:ios:523d14cbeb70cf82cced2d',
    messagingSenderId: '383298804056',
    projectId: 'thesisproject-f33a2',
    storageBucket: 'thesisproject-f33a2.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4O1RUpXPshz2cXIrInINKMh89bTYa89o',
    appId: '1:383298804056:web:b55b1fadd6265905cced2d',
    messagingSenderId: '383298804056',
    projectId: 'thesisproject-f33a2',
    authDomain: 'thesisproject-f33a2.firebaseapp.com',
    storageBucket: 'thesisproject-f33a2.firebasestorage.app',
    measurementId: 'G-JZN24NEMZD',
  );
}
